server:
  port: 8082

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/ordenes

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  group:
    aws: ordenes-log-group
